### ISSUE TITLE
This module uses http-browserify which is outdated

### ISSUE THREAD

**Issue by RomanHotsiy** [jspm/nodelibs-http#1]
From the `package.json` file I can see this module is [just mapped](https://github.com/jspm/nodelibs-http/blob/master/package.json#L7) to `http-browserify`.
However, `http-browserify` is deprecated and seems to not be maintained anymore: it has opened a whole bunch of issues and pull-requests and latest contribution was made 2years ago. Even browserify doesn't use it anymore: https://github.com/substack/https-browserify/issues/6#issuecomment-181135863

This causes lots of issue on my project. Can you update to use `stream-http`?

**Comment by guybedford** [comment]
In jspm 0.17 we're using `stream-http`, I'd suggest upgrading for the support.
